name: check
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
jobs:
  check-matchings:
    runs-on: ubuntu-latest
    steps:
    - uses: haya14busa/action-workflow_run-status@967ed83efa565c257675ed70cfe5231f062ddd94
    - uses: actions/checkout@v2
    - run: git submodule update --init --recursive
    - name: Install pip
      run: sudo apt update && sudo apt install -y python3-pip python3-setuptools gpg wget
    - name: Install tool dependencies
      run: sudo python3 -m pip install capstone colorama cxxfilt pyelftools
    - name: Download executable
      run: wget https://static.zeldamods.org/botw/16A91992BBA71201E98756F3BC8F5D2F.elf.gpg
    - name: Decrypt executable
      run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.leo_secret }}" --output data/main.elf 16A91992BBA71201E98756F3BC8F5D2F.elf.gpg
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@3cd20b2b63293848b29e22223f515baf725ed98f
      with:
        workflow: build.yml
        name: build
    - name: Check matchings
      run: tools/check.py
